#!/usr/bin/env python3
# -*-python-*-

import sys
import logging

import mapzen.whosonfirst.languages

if __name__ == "__main__":

    for tag in sys.argv[1:]:

        try:
            l = mapzen.whosonfirst.languages.language(tag)
        except Exception as e:
            logging.error("failed to parse %s, because %s" % (tag, e))
            continue

        print("language tag '%s' becomes %s" % (tag, l))



