#!/usr/bin/env python
# -*-python-*-

import sys

import mapzen.whosonfirst.languages

if __name__ == "__main__":

    for tag in sys.argv[1:]:

        l = mapzen.whosonfirst.languages.language(tag)
        print l



