#!/usr/bin/env python3
# -*-python-*-

import sys
import json
import mapzen.whosonfirst.languages.utils

if __name__ == '__main__':

    st = mapzen.whosonfirst.languages.utils.subtags()
    compiled = st.compile()

    json.dump(compiled, sys.stdout)
    sys.exit()
