#!/usr/bin/env python
# -*-python-*-

import sys
import json
import mapzen.whosonfirst.languages

if __name__ == '__main__':

    codes = mapzen.whosonfirst.languages.iso639()
    compiled = codes.compile()

    json.dump(compiled, sys.stdout)
    sys.exit()
